language: python

sudo: false

python:
  - 2.7
  - 3.4
  - 3.5

addons:
  apt:
    packages:
      mlocate

install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
  - pip install git+git://github.com/spacetelescope/asv.git@master
  - yes "" | asv machine

script:
  - asv run -q
